enum AppErrorTypes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNATHORIZED = 'UNATHORIZED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INCORRECT_EMAIL_OR_PASSWORD = 'INCORRECT_EMAIL_OR_PASSWORD',
  APPOINTMENT_ALREADY_BOOKED = 'APPOINTMENT_ALREADY_BOOKED',
}

export default AppErrorTypes;
